run doall:
	#rm -f *.bw *.bed.gz *.bedgraph.gz
	#bash combine.bsh
	#bash run_dREG.bsh mcf7.plus.bw mcf7.minus.bw mcf7_tamSR /local/storage/data/dREG-Model/asvm.mammal.RData 30
	#R --no-save < dge.R
	#R --no-save < motifEnrichment.R 
	#bash run_dREG.bsh ../data/sB7_pl.bw ../data/sB7_mn.bw sB7 /local/storage/data/dREG-Model/asvm.mammal.RData 15
	#bash run_dREG.bsh ../data/rG11_pl.bw ../data/rG11_mn.bw rG11 /local/storage/data/dREG-Model/asvm.mammal.RData 15
	bash run_dREG.bsh ../data/sC11_pl.bw ../data/sC11_mn.bw sC11 /local/storage/data/dREG-Model/asvm.mammal.RData 15
	bash run_dREG.bsh ../data/rH9_pl.bw ../data/rH9_mn.bw rH9 /local/storage/data/dREG-Model/asvm.mammal.RData 15
